// Code generated by "stringer -type=MatchingAlgorithm -output=matching_string.go"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MatchUnspecified-0]
	_ = x[MatchAny-1]
	_ = x[MatchAll-2]
	_ = x[MatchLiteral-3]
	_ = x[MatchRegex-4]
	_ = x[MatchFuzzy-5]
	_ = x[MatchAuto-6]
}

const _MatchingAlgorithm_name = "MatchUnspecifiedMatchAnyMatchAllMatchLiteralMatchRegexMatchFuzzyMatchAuto"

var _MatchingAlgorithm_index = [...]uint8{0, 16, 24, 32, 44, 54, 64, 73}

func (i MatchingAlgorithm) String() string {
	if i < 0 || i >= MatchingAlgorithm(len(_MatchingAlgorithm_index)-1) {
		return "MatchingAlgorithm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MatchingAlgorithm_name[_MatchingAlgorithm_index[i]:_MatchingAlgorithm_index[i+1]]
}
