// Code generated by "generate_models --output models_generated.go"; DO NOT EDIT.
package client

import "encoding/json"
import "time"

type Correspondent struct {
	ID                 int64             `json:"id"`
	Slug               string            `json:"slug"`
	Name               string            `json:"name"`
	Match              string            `json:"match"`
	MatchingAlgorithm  MatchingAlgorithm `json:"matching_algorithm"`
	IsInsensitive      bool              `json:"is_insensitive"`
	DocumentCount      int64             `json:"document_count"`
	LastCorrespondence *time.Time        `json:"last_correspondence"`

	// Object owner; objects without owner can be viewed and edited by all users.
	Owner *int64 `json:"owner"`
}

type CorrespondentFields struct {
	objectFields
}

var _ json.Marshaler = (*CorrespondentFields)(nil)

func NewCorrespondentFields() *CorrespondentFields {
	return &CorrespondentFields{objectFields{}}
}

func (f *CorrespondentFields) Name(name string) *CorrespondentFields {
	f.set("name", name)
	return f
}

func (f *CorrespondentFields) Match(match string) *CorrespondentFields {
	f.set("match", match)
	return f
}

func (f *CorrespondentFields) MatchingAlgorithm(matchingAlgorithm MatchingAlgorithm) *CorrespondentFields {
	f.set("matching_algorithm", matchingAlgorithm)
	return f
}

func (f *CorrespondentFields) IsInsensitive(isInsensitive bool) *CorrespondentFields {
	f.set("is_insensitive", isInsensitive)
	return f
}

func (f *CorrespondentFields) Owner(owner *int64) *CorrespondentFields {
	f.set("owner", owner)
	return f
}

type CustomField struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	DataType string `json:"data_type"`

	// Object owner; objects without owner can be viewed and edited by all users.
	Owner *int64 `json:"owner"`
}

type CustomFieldFields struct {
	objectFields
}

var _ json.Marshaler = (*CustomFieldFields)(nil)

func NewCustomFieldFields() *CustomFieldFields {
	return &CustomFieldFields{objectFields{}}
}

func (f *CustomFieldFields) Name(name string) *CustomFieldFields {
	f.set("name", name)
	return f
}

func (f *CustomFieldFields) DataType(dataType string) *CustomFieldFields {
	f.set("data_type", dataType)
	return f
}

func (f *CustomFieldFields) Owner(owner *int64) *CustomFieldFields {
	f.set("owner", owner)
	return f
}

type Document struct {
	// ID of the document.
	ID int64 `json:"id"`

	// Title of the document.
	Title string `json:"title"`

	// Plain-text content of the document.
	Content string `json:"content"`

	// List of tag IDs assigned to this document, or empty list.
	Tags []int64 `json:"tags"`

	// Document type of this document or nil.
	DocumentType *int64 `json:"document_type"`

	// Correspondent of this document or nil.
	Correspondent *int64 `json:"correspondent"`

	// Storage path of this document or nil.
	StoragePath *int64 `json:"storage_path"`

	// The date time at which this document was created.
	Created time.Time `json:"created"`

	// The date at which this document was last edited in paperless.
	Modified time.Time `json:"modified"`

	// The date at which this document was added to paperless.
	Added time.Time `json:"added"`

	// The identifier of this document in a physical document archive.
	ArchiveSerialNumber *int64 `json:"archive_serial_number"`

	// Verbose filename of the original document.
	OriginalFileName string `json:"original_file_name"`

	// Verbose filename of the archived document. Nil if no archived document is available.
	ArchivedFileName *string `json:"archived_file_name"`

	// Custom fields on the document.
	CustomFields []CustomFieldInstance `json:"custom_fields"`

	// Object owner; objects without owner can be viewed and edited by all users.
	Owner *int64 `json:"owner"`
}

type DocumentFields struct {
	objectFields
}

var _ json.Marshaler = (*DocumentFields)(nil)

func NewDocumentFields() *DocumentFields {
	return &DocumentFields{objectFields{}}
}

func (f *DocumentFields) Title(title string) *DocumentFields {
	f.set("title", title)
	return f
}

func (f *DocumentFields) Content(content string) *DocumentFields {
	f.set("content", content)
	return f
}

func (f *DocumentFields) Tags(tags []int64) *DocumentFields {
	f.set("tags", tags)
	return f
}

func (f *DocumentFields) DocumentType(documentType *int64) *DocumentFields {
	f.set("document_type", documentType)
	return f
}

func (f *DocumentFields) Correspondent(correspondent *int64) *DocumentFields {
	f.set("correspondent", correspondent)
	return f
}

func (f *DocumentFields) StoragePath(storagePath *int64) *DocumentFields {
	f.set("storage_path", storagePath)
	return f
}

func (f *DocumentFields) Created(created time.Time) *DocumentFields {
	f.set("created", created)
	return f
}

func (f *DocumentFields) ArchiveSerialNumber(archiveSerialNumber *int64) *DocumentFields {
	f.set("archive_serial_number", archiveSerialNumber)
	return f
}

func (f *DocumentFields) CustomFields(customFields []CustomFieldInstance) *DocumentFields {
	f.set("custom_fields", customFields)
	return f
}

func (f *DocumentFields) Owner(owner *int64) *DocumentFields {
	f.set("owner", owner)
	return f
}

type DocumentType struct {
	ID                int64             `json:"id"`
	Slug              string            `json:"slug"`
	Name              string            `json:"name"`
	Match             string            `json:"match"`
	MatchingAlgorithm MatchingAlgorithm `json:"matching_algorithm"`
	IsInsensitive     bool              `json:"is_insensitive"`
	DocumentCount     int64             `json:"document_count"`

	// Object owner; objects without owner can be viewed and edited by all users.
	Owner *int64 `json:"owner"`
}

type DocumentTypeFields struct {
	objectFields
}

var _ json.Marshaler = (*DocumentTypeFields)(nil)

func NewDocumentTypeFields() *DocumentTypeFields {
	return &DocumentTypeFields{objectFields{}}
}

func (f *DocumentTypeFields) Name(name string) *DocumentTypeFields {
	f.set("name", name)
	return f
}

func (f *DocumentTypeFields) Match(match string) *DocumentTypeFields {
	f.set("match", match)
	return f
}

func (f *DocumentTypeFields) MatchingAlgorithm(matchingAlgorithm MatchingAlgorithm) *DocumentTypeFields {
	f.set("matching_algorithm", matchingAlgorithm)
	return f
}

func (f *DocumentTypeFields) IsInsensitive(isInsensitive bool) *DocumentTypeFields {
	f.set("is_insensitive", isInsensitive)
	return f
}

func (f *DocumentTypeFields) Owner(owner *int64) *DocumentTypeFields {
	f.set("owner", owner)
	return f
}

type StoragePath struct {
	ID                int64             `json:"id"`
	Slug              string            `json:"slug"`
	Name              string            `json:"name"`
	Match             string            `json:"match"`
	MatchingAlgorithm MatchingAlgorithm `json:"matching_algorithm"`
	IsInsensitive     bool              `json:"is_insensitive"`
	DocumentCount     int64             `json:"document_count"`

	// Object owner; objects without owner can be viewed and edited by all users.
	Owner *int64 `json:"owner"`
}

type StoragePathFields struct {
	objectFields
}

var _ json.Marshaler = (*StoragePathFields)(nil)

func NewStoragePathFields() *StoragePathFields {
	return &StoragePathFields{objectFields{}}
}

func (f *StoragePathFields) Name(name string) *StoragePathFields {
	f.set("name", name)
	return f
}

func (f *StoragePathFields) Match(match string) *StoragePathFields {
	f.set("match", match)
	return f
}

func (f *StoragePathFields) MatchingAlgorithm(matchingAlgorithm MatchingAlgorithm) *StoragePathFields {
	f.set("matching_algorithm", matchingAlgorithm)
	return f
}

func (f *StoragePathFields) IsInsensitive(isInsensitive bool) *StoragePathFields {
	f.set("is_insensitive", isInsensitive)
	return f
}

func (f *StoragePathFields) Owner(owner *int64) *StoragePathFields {
	f.set("owner", owner)
	return f
}

type Tag struct {
	ID                int64             `json:"id"`
	Slug              string            `json:"slug"`
	Name              string            `json:"name"`
	Color             Color             `json:"color"`
	TextColor         Color             `json:"text_color"`
	Match             string            `json:"match"`
	MatchingAlgorithm MatchingAlgorithm `json:"matching_algorithm"`
	IsInsensitive     bool              `json:"is_insensitive"`
	IsInboxTag        bool              `json:"is_inbox_tag"`
	DocumentCount     int64             `json:"document_count"`

	// Object owner; objects without owner can be viewed and edited by all users.
	Owner *int64 `json:"owner"`
}

type TagFields struct {
	objectFields
}

var _ json.Marshaler = (*TagFields)(nil)

func NewTagFields() *TagFields {
	return &TagFields{objectFields{}}
}

func (f *TagFields) Name(name string) *TagFields {
	f.set("name", name)
	return f
}

func (f *TagFields) Color(color Color) *TagFields {
	f.set("color", color)
	return f
}

func (f *TagFields) TextColor(textColor Color) *TagFields {
	f.set("text_color", textColor)
	return f
}

func (f *TagFields) Match(match string) *TagFields {
	f.set("match", match)
	return f
}

func (f *TagFields) MatchingAlgorithm(matchingAlgorithm MatchingAlgorithm) *TagFields {
	f.set("matching_algorithm", matchingAlgorithm)
	return f
}

func (f *TagFields) IsInsensitive(isInsensitive bool) *TagFields {
	f.set("is_insensitive", isInsensitive)
	return f
}

func (f *TagFields) IsInboxTag(isInboxTag bool) *TagFields {
	f.set("is_inbox_tag", isInboxTag)
	return f
}

func (f *TagFields) Owner(owner *int64) *TagFields {
	f.set("owner", owner)
	return f
}
